### PR TITLE
updated statsmodels to 0.8.0rc1

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Looks like release-candidate support is being discussed: https://github.com/conda-forge/conda-forge.github.io/issues/147#

(though I would argue that the officially released statsmodels is ancient enough that an RC is a big improvement 😄)

Either way, I think the plan is for an official release in August, so perhaps it's better to wait?

**Comment by ericmjl** [comment]
😄 okay! There is a user (on the conda mailing list) wanting version 0.7.0 - would you think it'd be good to update this recipe to 0.7.0 first instead? I'll respect your decision on this one.

**Comment by jakirkham** [comment]
Would recommend sticking with a proper releases as well. Though definitely understand the pain of long release cycles.

**Comment by TomAugspurger** [comment]
@ericmjl I don't think that 0.7 was ever released to PyPI: https://pypi.org/project/statsmodels/0.8.0rc1/#history

**Comment by TomAugspurger** [comment]
Closing in favor of #3 (the final 0.8.0 release)

**Pull request closed without merging**
