### PR TITLE
RLS: Rebuild for release 0.12.0rc0

### PR DESCRIPTION
**Pull request by bashtage**
Rebuild RC0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bashtage** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
More details about how to publish RCs can be found here

https://github.com/conda-forge/cfep/blob/master/cfep-05.md

**Comment by bashtage** [comment]
@conda-forge-admin, please rerender

**Comment by bashtage** [comment]
@jakirkham do you know what I need to set to disable PPC LE builds? We don't test on this platform and it is having a hard time resolving for it. I don't think it needs to be included.

As for this PR, I think we may not merge it.  I mostly wanted to get it working for the actual release in a week or two.

**Comment by bashtage** [comment]
@jakirkham Seems like PPC at least builds, so I suppose we could just leave it in.

**Pull request closed without merging**
