### PR TITLE
RLS: v0.8.0

### PR DESCRIPTION
**Pull request by bashtage**
@TomAugspurger 's branch changes to attempt a new build.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@jakirkham does this look OK to you? I don't see an Appveyor build, is that normal?

My PR had appveyor (which passed), but no CircleCI. This PR has CircleCI, but no appveyor.

**Comment by jakirkham** [comment]
Sometimes AppVeyor runs into [GitHub rate limited](https://developer.github.com/v3/#rate-limiting ) so it won't show up. We have tried to mitigate various rate limiting issues over time. However, we have discovered in the past few months that AppVeyor on all the feedstocks uses one bot user for all GitHub operations, which is the same one shared with feedstock and team updates. The rate limiting period has ended. So I have triggered the webhook for AppVeyor manually, which appears to have fixed the issue. Though we will need to come up with a better long term fix.

xref: https://github.com/appveyor/ci/issues/1002
xref: https://github.com/conda-forge/conda-forge.github.io/issues/314

**Comment by jakirkham** [comment]
Maybe the title should be a bit more descriptive. Perhaps mention the release version. 😉

**Comment by bashtage** [comment]
Should I close this in favor of @TomAugspurger 's?

**Comment by bashtage** [comment]
Oh, I just saw the comment in #4 so I'll leave this one.

**Comment by jakirkham** [comment]
Yep, sorry, probably should have included some version of that comment here too.

**Comment by kain88-de** [comment]
@jakirkham the CI finished (appveyor as well). Can you merge this?

**Pull request merged**
