### PR TITLE
RLS: v0.8.0

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/conda-forge/statsmodels-feedstock/pull/3

### CODE REVIEW

**Comment by ocefpaf** [comment]
Does not look like a PR from a fork. What is the result of `git remote -v`?

**Comment by TomAugspurger** [comment]
```
origin	https://github.com/TomAugspurger/statsmodels-feedstock (fetch)
origin	https://github.com/TomAugspurger/statsmodels-feedstock (push)
upstream	https://github.com/conda-forge/statsmodels-feedstock (fetch)
upstream	https://github.com/conda-forge/statsmodels-feedstock (push)
```

**Comment by ocefpaf** [comment]
Something is odd there....

**Comment by TomAugspurger** [comment]
Very strange...

Earlier today, when I did my first push (to `origin` or `TomAugspurger/statsmodels-feedstock`), that repo was *not* a fork of `conda-forge/statsmodels-feedstock`. I must have messed that up when I made the initial recipe?

So I deleted `TomAugspurger/statsmodels-feedstock`, and forked `conda-forge/statsmodels-feedstock`. Updated my remotes.

**Comment by jakirkham** [comment]
This PR is from @TomAugspurger fork. One can see `TomAugspurger:v0.8.0` at the top. Am I missing something? 😕

Would also add that CI statuses are per commit not per PR. So if this shared the latest commit from the old PR ( 95a9502678ce8394da4767d273bf2923033c3379 ), then it would show up with CIs from the old PR. Later commits or an amended commit (changed sha) won't have this issue. Perhaps this is what caused confusion.

**Comment by TomAugspurger** [comment]
> Later commits or an amended commit (changed sha) won't have this issue.

Seems like Travis and Appveyor picked up b785a88 (just an empty commit), but not CircleCI. Sorry about this mess, I'll keep looking :/

**Comment by bashtage** [comment]
Is this working now?

**Comment by jakirkham** [comment]
Not sure why CircleCI didn't work here and there is no indication from the webhook why it failed (it actually claims to have succeeded 😕). In any event, it seems PR ( https://github.com/conda-forge/statsmodels-feedstock/pull/5 ) is working. So maybe we can close this and just chalk it up as anomaly for now. If we do start seeing repeated issues with CircleCI, we can take a closer look.

**Pull request closed without merging**
