### PR TITLE
RLS: v0.8.0

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by croth1** [comment]
👍 I'm wondering if we really need jinja templates for the name and the build number.  This might interfere with some scripts that are automatically sending PRs.

Also we may want to switch to sha256

**Comment by TomAugspurger** [comment]
The failure [here](https://ci.appveyor.com/project/conda-forge/statsmodels-feedstock/build/1.0.6) looks like a network issue. Will I need to retrigger the entire build process?

**Comment by ocefpaf** [comment]
Please send PRs from a fork. Not only that waste precious CI time by triggering Travis-CI twice but it also causes a premature upload of the package before the merge.

**Comment by TomAugspurger** [comment]
> Please send PRs from a fork

Sorry about that. Apparently my `TomAugspurger/statsmodels-feedstock` wasn't a fork originally. At this point, is it better to close this PR?

**Comment by ocefpaf** [comment]
I recommend closing.

**Pull request closed without merging**
