### PR TITLE
RLS: Release 0.13 build

### PR DESCRIPTION
**Pull request by bashtage**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bashtage** [comment]
@conda-forge-admin, please rerender

**Comment by bashtage** [comment]
@conda-forge-admin, please rerender

**Comment by bashtage** [comment]
@isuruf Any idea how to disable osx-arm?  We don't have any support for this and we have lots of evidence that statsmodels doesn't work correctly on ARM due to Blas issues (testing on gravitron/Linux).

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by croth1** [comment]
thanks so much @bashtage. Do you maybe want to add yourself to the maintainer team so that you get the rights to merge PRs here?

**Comment by bashtage** [comment]
@croth1 I think I did in the recipe.

**Comment by bashtage** [comment]
Looks ready to merge.

**Comment by bashtage** [comment]
Thanks.

**Pull request merged**
